# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterevent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='locationId',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventId',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='locLatitude',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='locLongitude',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='locationId',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
