# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterevent', '0002_auto_20170408_1616'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
