# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterevent', '0003_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.IntegerField()),
                ('eventId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeId', models.IntegerField()),
                ('capacity', models.FloatField(verbose_name=20)),
                ('sourceLocation', models.IntegerField()),
                ('endLocation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.IntegerField()),
                ('regionName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorId', models.IntegerField()),
                ('volume', models.FloatField()),
                ('phLevel', models.IntegerField()),
                ('contaminantLevel', models.FloatField()),
                ('date', models.DateField()),
                ('observId', models.IntegerField()),
            ],
        ),
    ]
